### ISSUE TITLE
small comment

### ISSUE THREAD

**Issue by kingjr** [kilimanjaro/earley#1]
Hi,

I think https://github.com/kilimanjaro/earley/blob/master/parser.py#L37 is superfluous, no?

**Comment by kingjr** [comment]
and so is the condition `if item.rest == ()` in line 22

**Comment by braised-babbage** [comment]
Nice catch, I've removed that check from line 37. Line 22 is ok I think -- even though it's not necessary given how `predictions` is called by `earley_table`

**Comment by kingjr** [comment]
yep. In any case, thanks for sharing, that was really useful for me to learn how Earley worked!

I uploaded a more scripted version here: https://gist.github.com/kingjr/a80a0d174166a99c5d19022ce086fe7c
